### ISSUE TITLE
Easy way to add documentation to specs, st/doc?

### ISSUE THREAD

**Issue by ikitommi** [metosin/spec-tools#12]
```clj
(s/def ::age (st/doc integer? {:description "It's and id"}))

(st/coll-spec
  ::person
  {:id (st/doc integer? {:description "id"})
   :age ::age})
```

**Comment by xuwhao** [comment]
I want to ad a documentation to specs so that it can show in swagger, what should I do ?  I can not find 'st/doc' in namespace 'spec-tools.core'. 

I want to it can be here.
![image](https://user-images.githubusercontent.com/46437721/116509638-3fc18380-a8f6-11eb-9bb2-b3a6ac107635.png)

and the data came from here.
![image](https://user-images.githubusercontent.com/46437721/116509691-52d45380-a8f6-11eb-99dd-9859ab3add6d.png)

It corresponds to this field
![image](https://user-images.githubusercontent.com/46437721/116509527-0be65e00-a8f6-11eb-93ae-00cb4a633c4a.png)
