### ISSUE TITLE
swagger/transform is not compliant with openapi2

### ISSUE THREAD

**Issue by asilverman** [metosin/spec-tools#193]
When transforming the following payload:
```
(spec-tools.swagger.core/transform  sequential?)
;;=> {:type "array"}
```
causes a validation error on openapi2 as following
```
Schemas with 'type: array', require a sibling 'items: ' field
```
in the case the system cannot derive the items value, it should default to `object`

**Comment by miikka** [comment]
Ah, this is one more incompatibility between JSON Schema and OpenAPI 2.0. The Swagger/OpenAPI 2.0 generation in spec-tools is based on the JSON Schema generation. I believe this could be fixed by adding a suitable `accept-spec` method to [swagger/core.cljc](https://github.com/metosin/spec-tools/blob/master/src/spec_tools/swagger/core.cljc) to override the one in [json_schema.cljc](https://github.com/metosin/spec-tools/blob/master/src/spec_tools/json_schema.cljc#L169-L170). A PR to fix this would be welcome.
