### ISSUE TITLE
Generate JSON Schemas from clojure.specs

### ISSUE THREAD

**Issue by ikitommi** [metosin/spec-tools#4]
- related: https://github.com/metosin/ring-swagger/issues/95
- initial vomitation: https://github.com/metosin/spec-tools/tree/spec-parsing

**Comment by miikka** [comment]
I didn't really understand what the spec-parsing branch, but here's my sketch of this: https://github.com/miikka/spec-tools/commit/8a52296aca3f7bc5b1f89b165389aea2d4d94b2c

**Comment by miikka** [comment]
I looked at [arohner/spectrum](https://github.com/arohner/spectrum) again and it might make sense to take my tests and write a version based on spectrum against them.

**Comment by miikka** [comment]
I have some [some new code](https://github.com/metosin/spec-tools/compare/json-schema/more-primitive-types?expand=1), but unfortunately right now the predicates for collection specs aren't resolved by the clojure.spec macros. This prevents `spec-tools.json-schema` from recognizing them. Hopefully it's fixed soon, the bug is here: [CLJ-2035](http://dev.clojure.org/jira/browse/CLJ-2035).

**Comment by ikitommi** [comment]
Nice. 

Is it possible to configure how the JSON Schema generation process works? For example, the Swagger JSON Schema doesn't currently allow `null`s, `any-of` or `one-of`s.

**Comment by miikka** [comment]
Progress report: as of #13, the `::person` example from README can be converted into reasonable JSON Schema. CLJ-2035 is still open, but it can be worked around by fully qualifying the predicates when writing the specs.

I'm not sure what should be done w.r.t. Swagger - maybe spec-tools should only target the Swagger-compliant JSON Schema, since that's probably the main use case anyway - or maybe it should be somehow configurable, or maybe there should a separate function for that.

**Comment by ikitommi** [comment]
Awesome! I think both are valid cases in the future: swagger & pure json schema. Looking forward to see / hear how these should be separated. Also, we should be able to collect all map-specs from a nested definition and optionally convert to `$ref`s for better reuse. I have a use case for "collect ALL registered referenced specs", so that should be doable too.

**Comment by ikitommi** [comment]
`s/merge` is the last to  be implemented.

**Comment by ikitommi** [comment]
done!
